services:
  dyndns:
    build: dyndns
    volumes:
      - ./dyndns/settings.txt:/settings.txt

  unbound:
    build: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254

  memcached:
    image: memcached:alpine
    restart: always
    networks:
      mail-network:
        aliases:
          - memcached

  mysql:
    image: mariadb:10.5
    depends_on:
      - unbound
    user: mysql
    stop_grace_period: 45s
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/:ro,Z
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      - mail-network

  redis:
    image: redis:7-alpine
    entrypoint: /docker-entrypoint.sh
    command: redis-server /redis.conf
    volumes:
      - ./redis/docker-entrypoint.sh:/docker-entrypoint.sh:Z
      - redis-vol-1:/data/
    restart: always
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    environment:
      - REDISPASS=${REDISPASS}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249

  frontend:
    build:
      context: frontend
      target: prod
    ports:
      - "${FRONTEND_PORT:-127.0.0.1:3000}:3000"
    restart: always
    networks:
      - mail-network

  api:
    build: backend
    command: >
      bash -c "alembic upgrade head
      && uvicorn --host=0.0.0.0 --port=80 taram.api:app --log-config=/app/log-config.yaml"
    restart: always
    depends_on:
      - dockerapi
      - memcached
      - mysql
      - redis
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - DBDRIVER=mysql
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    volumes:
      - mysql-socket-vol-1:/var/run/mysqld/
    networks:
      - mail-network

  clamd:
    image: clamav/clamav:1.4.1
    restart: always
    depends_on:
      - unbound
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - ./clamd/clamd.conf:/etc/clamav/clamd.conf:ro,Z
      - ./clamd/freshclam.conf:/etc/clamav/freshclam.conf:ro,Z
      - clamd-vol-1:/var/lib/clamav
    networks:
      - mail-network

  rspamd:
    build: rspamd
    stop_grace_period: 30s
    depends_on:
      - clamd
      - dovecot
      - redis
    environment:
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    volumes:
      - ./rspamd/custom/:/etc/rspamd/custom:z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      - mail-network

  postfix:
    build: postfix
    depends_on:
      - api
      - mysql
      - redis
      - unbound
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
    volumes:
      - ./postfix/conf:/opt/postfix/conf:z
      - ./ssl:/etc/ssl/mail/:ro,z
      - postfix-vol-1:/var/spool/postfix
      - crypt-vol-1:/var/lib/zeyple
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.253

  dovecot:
    build: dovecot
    depends_on:
      - mysql
      - netfilter
      - redis
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./dovecot/conf:/etc/dovecot:z
      - ./dovecot/templates:/templates:z
      - ./ssl:/etc/ssl/mail/:ro,z
      - ./sogo/conf/:/etc/sogo/:z
      - vmail-vol-1:/var/vmail
      - vmail-index-vol-1:/var/vmail_index
      - crypt-vol-1:/mail_crypt/
      - ./rspamd/custom/:/etc/rspamd/custom:z
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - DOVECOT_MASTER_USER=${DOVECOT_MASTER_USER:-}
      - DOVECOT_MASTER_PASS=${DOVECOT_MASTER_PASS:-}
      - MAIL_REPLICA_IP=${MAIL_REPLICA_IP:-}
      - DOVEADM_REPLICA_PORT=${DOVEADM_REPLICA_PORT:-}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-7200}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - SKIP_FTS=${SKIP_FTS:-n}
      - MAILDIR_SUB=${MAILDIR_SUB:-}
      - MASTER=${MASTER:-y}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-taram}
      - FLATCURVE_EXPERIMENTAL=${FLATCURVE_EXPERIMENTAL:-n}
    ports:
      - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    tty: true
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dovecot_imapsync_runner.schedule: "@every 1m"
      ofelia.job-exec.dovecot_imapsync_runner.no-overlap: "true"
      ofelia.job-exec.dovecot_imapsync_runner.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu nobody /usr/local/bin/imapsync_runner.pl || exit 0\""
      ofelia.job-exec.dovecot_trim_logs.schedule: "@every 1m"
      ofelia.job-exec.dovecot_trim_logs.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu vmail /usr/local/bin/trim_logs.sh || exit 0\""
      ofelia.job-exec.dovecot_quarantine.schedule: "@every 20m"
      ofelia.job-exec.dovecot_quarantine.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu vmail /usr/local/bin/quarantine_notify.py || exit 0\""
      ofelia.job-exec.dovecot_clean_q_aged.schedule: "@every 24h"
      ofelia.job-exec.dovecot_clean_q_aged.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu vmail /usr/local/bin/clean_q_aged.sh || exit 0\""
      ofelia.job-exec.dovecot_maildir_gc.schedule: "@every 30m"
      ofelia.job-exec.dovecot_maildir_gc.command: "/bin/bash -c \"source /source_env.sh ; /usr/local/bin/gosu vmail /usr/local/bin/maildir_gc.sh\""
      ofelia.job-exec.dovecot_sarules.schedule: "@every 24h"
      ofelia.job-exec.dovecot_sarules.command: "/bin/bash -c \"/usr/local/bin/sa-rules.sh\""
      ofelia.job-exec.dovecot_fts.schedule: "@every 24h"
      ofelia.job-exec.dovecot_fts.command: "/bin/bash -c \"/usr/local/bin/gosu vmail /usr/local/bin/optimize-fts.sh\""
      ofelia.job-exec.dovecot_repl_health.schedule: "@every 5m"
      ofelia.job-exec.dovecot_repl_health.command: "/bin/bash -c \"/usr/local/bin/gosu vmail /usr/local/bin/repl_health.sh\""
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.250

  sogo:
    build: sogo
    depends_on:
      - api
      - redis
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - SOGO_EXPIRE_SESSION=${SOGO_EXPIRE_SESSION:-480}
      - MASTER=${MASTER:-y}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - TZ=${TZ}
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - ./sogo/conf/:/etc/sogo/:z
      - ./sogo/sogo.ico:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo.ico:z
      - ./sogo/theme.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/theme.js:z
      - mysql-socket-vol-1:/var/run/mysqld/
      - sogo-web-vol-1:/sogo_web
      - sogo-userdata-backup-vol-1:/sogo_backup
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sogo_sessions.schedule: "@every 1m"
      ofelia.job-exec.sogo_sessions.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool -v expire-sessions $${SOGO_EXPIRE_SESSION} || exit 0\""
      ofelia.job-exec.sogo_ealarms.schedule: "@every 1m"
      ofelia.job-exec.sogo_ealarms.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-ealarms-notify -p /etc/sogo/cron.creds || exit 0\""
      ofelia.job-exec.sogo_eautoreply.schedule: "@every 5m"
      ofelia.job-exec.sogo_eautoreply.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool update-autoreply -p /etc/sogo/cron.creds || exit 0\""
      ofelia.job-exec.sogo_backup.schedule: "@every 24h"
      ofelia.job-exec.sogo_backup.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool backup /sogo_backup ALL || exit 0\""
    restart: always
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.248

  nginx:
    build: nginx
    depends_on:
      - redis
      - api
      - frontend
      - sogo
      - rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTP_PORT=${HTTP_PORT:-80}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
      - TZ=${TZ}
      - SKIP_SOGO=${SKIP_SOGO:-n}
      - SKIP_RSPAMD=${SKIP_RSPAMD:-n}
      - DISABLE_IPv6=${DISABLE_IPv6:-n}
      - SOGOHOST=${SOGOHOST:-}
      - RSPAMDHOST=${RSPAMDHOST:-}
      - REDISHOST=${REDISHOST:-}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
    volumes:
      - ./acme/.well-known:/web/.well-known:ro,z
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - ./ssl/:/etc/ssl/mail/:ro,z
      - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
    ports:
      - "${HTTPS_BIND:-}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "${HTTP_BIND:-}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    restart: always
    networks:
      - mail-network

  acme:
    build: acme
    depends_on:
      - nginx
      - unbound
      - dockerapi
      - dovecot
      - mysql
      - postfix
      - redis
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - ACME_CONTACT=${ACME_CONTACT:-}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - AUTODISCOVER_SAN=${AUTODISCOVER_SAN:-y}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DIRECTORY_URL=${DIRECTORY_URL:-}
      - ENABLE_SSL_SNI=${ENABLE_SSL_SNI:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_MAIL_HOSTNAME=${ONLY_MAIL_HOSTNAME:-n}
      - LE_STAGING=${LE_STAGING:-n}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
    volumes:
      - ./acme/.well-known/acme-challenge:/var/www/acme:z
      - ./ssl:/var/lib/acme/:z
      - ./ssl-example:/var/lib/ssl-example/:ro,Z
      - mysql-socket-vol-1:/var/run/mysqld/
    restart: always
    networks:
      - mail-network

  netfilter:
    build: backend
    command: netfilter
    stop_grace_period: 30s
    restart: always
    privileged: true
    environment:
      - NETFILTER_CHAIN_NAME=${NETFILTER_CHAIN_NAME:-MAIL}
      - NETFILTER_CHAIN_COMMENT=${NETFILTER_CHAIN_COMMENT:-mail}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    network_mode: "host"
    volumes:
      - /lib/modules:/lib/modules:ro

  dockerapi:
    build: backend
    command: uvicorn --host=0.0.0.0 --port=80 taram.dockerapi:app --log-config=/app/log-config.yaml
    security_opt:
      - label=disable
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-taram}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mail-network

  monit:
    build: monit
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    depends_on:
      - acme
      - dockerapi
      - mysql
      - redis
    ports:
      - "${MONIT_PORT:-127.0.0.1:2812}:2812"
    volumes:
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - REDISPASS=${REDISPASS}
    networks:
      - mail-network

  ipv6nat:
    image: robbertkl/ipv6nat
    depends_on:
      - acme
      - clamd
      - dovecot
      - dockerapi
      - memcached
      - monit
      - mysql
      - netfilter
      - nginx
      - postfix
      - redis
      - rspamd
      - sogo
      - unbound
    security_opt:
      - label=disable
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  mail-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mail
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  clamd-vol-1:
  crypt-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  postfix-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  sogo-web-vol-1:
  sogo-userdata-backup-vol-1:
  vmail-vol-1:
  vmail-index-vol-1:
