global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mail'
    replica: '1'

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['taramail-api:80']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://taramail-nginx:443
          - http://taramail-sogo:20000/SOGo.index/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-imap'
    metrics_path: /probe
    params:
      module: [imap_starttls]
    static_configs:
      - targets:
          - taramail-dovecot:143
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-imaps'
    metrics_path: /probe
    params:
      module: [imap_tls]
    static_configs:
      - targets:
          - taramail-dovecot:993
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-redis'
    metrics_path: /probe
    params:
      module: [redis_check]
    static_configs:
      - targets:
          - taramail-redis:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-smtp-dovecot'
    metrics_path: /probe
    params:
      module: [smtp_lmtp_dovecot]
    static_configs:
      - targets:
          - taramail-dovecot:24
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-smtp-postfix'
    metrics_path: /probe
    params:
      module: [smtp_starttls]
    static_configs:
      - targets:
          - taramail-postfix:589
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - taramail-dovecot:4190
          - taramail-dovecot:10001
          - taramail-unbound:53
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: taramail-blackbox-exporter:9115

  - job_name: 'custom-checks'
    metrics_path: /check
    params:
      rspamd_host: [rspamd]
    static_configs:
      - targets: ['taramail-custom-exporter:80']

  - job_name: 'dockerapi'
    static_configs:
      - targets: ['taramail-dockerapi:80']

  - job_name: 'dovecot'
    static_configs:
      - targets: ['taramail-dovecot:9166']

  - job_name: 'mysql'
    static_configs:
      - targets: ['taramail-mysqld-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['taramail-nginx-exporter:9113']

  - job_name: 'postfix'
    static_configs:
      - targets: ['taramail-postfix-exporter:9154']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['taramail-prometheus:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['taramail-redis-exporter:9121']

  - job_name: 'rspamd'
    static_configs:
      - targets: ['taramail-rspamd:11334']
    metrics_path: '/metrics'
