global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mail'
    replica: '1'

scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://nginx:443
          - http://sogo:20000/SOGo.index/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-imap'
    metrics_path: /probe
    params:
      module: [imap_starttls]
    static_configs:
      - targets:
          - dovecot:143
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-imaps'
    metrics_path: /probe
    params:
      module: [imap_tls]
    static_configs:
      - targets:
          - dovecot:993
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-redis'
    metrics_path: /probe
    params:
      module: [redis_check]
    static_configs:
      - targets:
          - redis:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-smtp-dovecot'
    metrics_path: /probe
    params:
      module: [smtp_lmtp_dovecot]
    static_configs:
      - targets:
          - dovecot:24
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-smtp-postfix'
    metrics_path: /probe
    params:
      module: [smtp_starttls]
    static_configs:
      - targets:
          - postfix:589
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - dovecot:4190
          - dovecot:10001
          - unbound:53
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'custom-checks'
    metrics_path: /check
    params:
      rspamd_host: [rspamd]
    static_configs:
      - targets: ['custom-exporter:80']

  - job_name: 'dovecot'
    static_configs:
      - targets: ['dovecot:9166']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postfix'
    static_configs:
      - targets: ['postfix-exporter:9154']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rspamd'
    static_configs:
      - targets: ['rspamd:11334']
    metrics_path: '/metrics'
